//
// Created by Vitali Kurlovich on 3/17/16.
//

#ifndef RMVECTORMATH_TAFFINEVECTOR4_FUNC_INTERPOLATION_HPP
#define RMVECTORMATH_TAFFINEVECTOR4_FUNC_INTERPOLATION_HPP

#endif //RMVECTORMATH_TAFFINEVECTOR4_FUNC_INTERPOLATION_HPP
