//
// Created by Vitali Kurlovich on 5/16/16.
//

#ifndef RMVECTORMATH_TIDENTITYQUATERNION_FUNC_HPP
#define RMVECTORMATH_TIDENTITYQUATERNION_FUNC_HPP

#endif //RMVECTORMATH_TIDENTITYQUATERNION_FUNC_HPP
